sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
before_script:
  - npm prune
after_success:
  - npm run dist && npm run semantic-release
branches:
  except:
    # ignore git tags created by semantic-release, like "v1.2.3"
    - /^v\d+\.\d+\.\d+$/
