// Application
export const SIGNED_IN = 'SIGNED_IN'
export const SIGN_OUT = 'SIGN_OUT'

// Accounts
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const SHOW_ACCOUNT = 'SHOW_ACCOUNT'
export const GET_ACCOUNT = 'GET_ACCOUNT'
export const REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS'
export const REQUEST_ACCOUNT = 'REQUEST_ACCOUNT'
export const RECEIVED_ACCOUNTS = 'RECEIVED_ACCOUNTS'
export const RECEIVED_ACCOUNT = 'RECEIVED_ACCOUNT'
export const PURGE_CACHE = 'PURGE_CACHE'
export const SAVE_ACCOUNT = 'SAVE_ACCOUNT'
export const ACCOUNT_SAVED = 'ACCOUNT_SAVED'
export const SHOW_ACCOUNTS = 'SHOW_ACCOUNTS'
